global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ticket-service
    metrics_path: /metrics
    static_configs:
      - targets: ["ticket-service:8000"]

  - job_name: support-service
    metrics_path: /metrics
    static_configs:
      - targets: ["support-service:8000"]

  - job_name: reporting-service
    metrics_path: /metrics
    static_configs:
      - targets: ["reporting-service:8000"]

  - job_name: notification-service
    metrics_path: /metrics
    static_configs:
      - targets: ["notification-service:8000"]
